# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665cb0456a593fcdb7a8efbbef47c7b12d08b7c0701063ddbd74a6e949134c566324cc9f8b51f6e24f4a425b247d3f05f7c5840fe39362415e951e84c2670bfb

test:
  secret_key_base: 785dd0c79f06eb2f3e5cb3f4c477a140547e606cfed075fd46d141bf1938d14ac1831e54f6543c7668f9752f69444c8d1b36494cec288f080dfec88c771fc785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
